-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "McMojave-cursors")
hl.env("XCURSOR_SIZE", "32")

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
    },
    decoration = {
        blur = {
            size = 4,
        },
    },
    general = {
        border_size = 2,
    },
    input = {
        accel_profile = "flat",
    },
    misc = {
        vrr = 0,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1200@60.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
